使用pickle序列化numpy array

In [1]:
import pickle

In [2]:
import numpy as np

In [3]:
x = np.arange(10)

In [4]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
f = open('x.pkl', 'wb')

In [6]:
pickle.dump(x, f)

In [7]:
!ls

'ls' 不是内部或外部命令，也不是可运行的程序
或批处理文件。


In [8]:
f = open('x.pkl', 'rb')

In [9]:
pickle.load(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.save('one_array',x)

In [12]:
np.load('one_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
y = np.arange(20)

In [14]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
np.savez('two_array', a=x, b=y)

In [18]:
c = np.load('two_array.npz')

In [19]:
c['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
c['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])