数组的创建和访问

In [1]:
import numpy as np

In [6]:
list_1 = [1, 2, 3, 4]

In [5]:
list_1

[1, 2, 3, 4]

In [7]:
array_1 = np.array(list_1)

In [8]:
array_1

array([1, 2, 3, 4])

In [9]:
list_2 = [5, 6, 7, 8]

In [10]:
array_2 = np.array([list_1, list_2])

In [11]:
array_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
array_2.shape

(2, 4)

In [13]:
array_2.size

8

In [14]:
array_2.dtype

dtype('int32')

In [18]:
array_3 = np.array([[1.0, 2, 3], [4.0, 5, 6]])

In [19]:
array_3.dtype

dtype('float64')

In [20]:
array_4 = np.arange(1, 10)

In [21]:
array_4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros([2, 5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [25]:
a = np.array([[1,2,3],[4,5,6],7,8,9])

<ipython-input-25-9ce24a20af11>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([[1,2,3],[4,5,6],7,8,9])
