快速创建数组

In [1]:
import numpy as np

In [2]:
np.random.randn(10)

array([ 0.60460877,  0.55785861, -0.86045106, -1.12935641, -2.38518761,
       -2.02435572, -1.29424244,  1.22441981, -0.798797  , -0.733015  ])

In [3]:
np.random.randint(10)

6

In [4]:
np.random.randint(10, size=(3, 4))

array([[2, 5, 9, 0],
       [1, 2, 7, 5],
       [6, 4, 9, 9]])

In [5]:
np.random.randint(10, size=10)

array([0, 2, 4, 2, 6, 7, 8, 7, 5, 6])

In [7]:
np.random.randint(10, size=20).reshape(4, 5)

array([[9, 4, 2, 5, 8],
       [1, 6, 8, 6, 1],
       [2, 0, 5, 1, 2],
       [2, 9, 0, 5, 6]])

数组运算

In [8]:
a = np.random.randint(10, size=20).reshape(4, 5)

In [9]:
b = np.random.randint(10, size=20).reshape(4, 5)

In [10]:
a


array([[3, 2, 2, 0, 7],
       [8, 1, 2, 8, 2],
       [5, 9, 1, 0, 3],
       [5, 3, 6, 1, 9]])

In [11]:
b

array([[1, 4, 4, 2, 1],
       [3, 2, 6, 5, 1],
       [5, 6, 1, 4, 6],
       [3, 0, 2, 8, 2]])

In [12]:
a + b

array([[ 4,  6,  6,  2,  8],
       [11,  3,  8, 13,  3],
       [10, 15,  2,  4,  9],
       [ 8,  3,  8,  9, 11]])

In [13]:
a - b

array([[ 2, -2, -2, -2,  6],
       [ 5, -1, -4,  3,  1],
       [ 0,  3,  0, -4, -3],
       [ 2,  3,  4, -7,  7]])

In [14]:
a * b 


array([[ 3,  8,  8,  0,  7],
       [24,  2, 12, 40,  2],
       [25, 54,  1,  0, 18],
       [15,  0, 12,  8, 18]])

In [15]:
a / b

<ipython-input-15-d8e10abd5ab6>:1: RuntimeWarning: divide by zero encountered in true_divide
  a / b


array([[3.        , 0.5       , 0.5       , 0.        , 7.        ],
       [2.66666667, 0.5       , 0.33333333, 1.6       , 2.        ],
       [1.        , 1.5       , 1.        , 0.        , 0.5       ],
       [1.66666667,        inf, 3.        , 0.125     , 4.5       ]])

In [16]:
np.mat([[1,2,3],[4,5,6]])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [17]:
np.mat(a)

matrix([[3, 2, 2, 0, 7],
        [8, 1, 2, 8, 2],
        [5, 9, 1, 0, 3],
        [5, 3, 6, 1, 9]])

矩阵的运算

In [18]:
A = np.mat(a)
B = np.mat(b)

In [19]:
A

matrix([[3, 2, 2, 0, 7],
        [8, 1, 2, 8, 2],
        [5, 9, 1, 0, 3],
        [5, 3, 6, 1, 9]])

In [20]:
A + B

matrix([[ 4,  6,  6,  2,  8],
        [11,  3,  8, 13,  3],
        [10, 15,  2,  4,  9],
        [ 8,  3,  8,  9, 11]])

In [21]:
A - B


matrix([[ 2, -2, -2, -2,  6],
        [ 5, -1, -4,  3,  1],
        [ 0,  3,  0, -4, -3],
        [ 2,  3,  4, -7,  7]])

In [22]:
A - b


matrix([[ 2, -2, -2, -2,  6],
        [ 5, -1, -4,  3,  1],
        [ 0,  3,  0, -4, -3],
        [ 2,  3,  4, -7,  7]])

In [23]:
A * b

ValueError: shapes (4,5) and (4,5) not aligned: 5 (dim 1) != 4 (dim 0)

In [24]:
A * B

ValueError: shapes (4,5) and (4,5) not aligned: 5 (dim 1) != 4 (dim 0)

In [25]:
c = np.mat(np.random.randint(10, size=20).reshape(4, 5))
d = np.mat(np.random.randint(10, size=20).reshape(5, 4))

In [26]:
c * d

matrix([[165, 233, 121,  90],
        [111, 119,  35,  17],
        [192, 225, 105,  74],
        [ 77, 122,  56,  24]])

In [27]:
c
d

matrix([[3, 7, 4, 1],
        [5, 9, 1, 0],
        [2, 2, 9, 4],
        [8, 4, 0, 1],
        [8, 9, 1, 6]])

In [28]:
c

matrix([[8, 9, 8, 2, 8],
        [8, 3, 0, 9, 0],
        [7, 9, 7, 9, 5],
        [8, 5, 2, 2, 1]])

In [29]:
c.unipue

AttributeError: 'matrix' object has no attribute 'unipue'

In [36]:
np.unique(a)

array([0, 1, 2, 3, 5, 6, 7, 8, 9])

In [32]:
np.sum(a)

77

In [34]:
sum(a)

array([21, 15, 11,  9, 21])

In [35]:
sum(a[0])

14

In [37]:
sum(a[:, 0])

21

In [38]:
a

array([[3, 2, 2, 0, 7],
       [8, 1, 2, 8, 2],
       [5, 9, 1, 0, 3],
       [5, 3, 6, 1, 9]])

In [39]:
max(a)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [40]:
a.max()

9

In [41]:
a.max(0)

array([8, 9, 6, 8, 9])

In [42]:
a.max(a[0])

TypeError: only integer scalar arrays can be converted to a scalar index

In [43]:
max(a[0])

7

In [44]:
max(a[:, 0])

8